- Wedit-Client/src/components/loginpage/LoginButton.jsx
- Wedit-Client/src/components/mainpage/MainBannerSidebar.jsx
- Wedit-Client/src/components/mainpage/MainBannerSlider.jsx
- Wedit-Client/src/components/mainpage/MainPageFooter.jsx
- Wedit-Client/src/components/mainpage/PreviewInvitationButton.jsx
- Wedit-Client/src/components/mypage/Content.jsx
- Wedit-Client/src/components/mypage/InvitationButton.jsx
- Wedit-Client/src/components/mypage/MakingInvitation.jsx
- Wedit-Client/src/pages/HomePage.jsx
- Wedit-Client/src/styles/theme.js
- Closes #30 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
컬러코드 세팅
1. 컬러코드 세팅 완료
2. 적용 테스트 완료
**주의**
gray, green은 마지막이 배열 값입니다!
IntelliSense(인텔리센스)를 이용하면 자동으로 배열로 바뀌어 적용됩니다!
직접 치신다면 문법을 확인해주세요!
예시 )
> [Feat/#30] 컬러코드 세팅

- Wedit-Client/src/components/editpage/ThemeSelectModal.jsx
- Wedit-Client/src/components/mypage/InvitationButton.jsx
Closes #35
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
청첩장 제작하기 버튼 클릭 시 나타나는 테마 선택 Modal 컴포넌트 구현
1. 제작 페이지 테마 선택 modal 구현
2. 이동 버튼 페이지 연결
> [Feat/#35] 제작 페이지 테마 선택 Modal 컴포넌트 구현

- Wedit-Client/src/App.jsx
- Wedit-Client/src/components/mainpage/PreviewInvitationButton.jsx
- Wedit-Client/src/pages/PreviewInvitationPage.jsx
- Closes #37 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
청첩장 미리보기 페이지 구현
1. 미리보기 버튼 - 미리보기 페이지 nav 연결
2. 미리보기 페이지 기본형 청첩장 화면 구현(svg 파일 구성)
> [Feat/#37] 청첩장 미리보기 페이지 구현

- Wedit-Client/src/components/mainpage/CreatInvitationButton.jsx
- Wedit-Client/src/components/mainpage/CreateInvitationButton.jsx
- Wedit-Client/src/components/mainpage/MainPageHeader.jsx
- Closes #39 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
홈페이지 청첩장 제작하기 버튼 구현
1. 홈페이지 청첩장 제작하기 버튼 생성(api 연결 X)
2. 버튼 nav 연결(edit 페이지)
3. 토큰 관리 안 되어 있어 로그인 버튼 또는 제작하기 버튼 주석처리 하여 작업
> [Feat/#39] 홈페이지 청첩장 제작하기 버튼 구현

- Wedit-Client/src/components/PhotoSelectionPage/PhotoSelectionButton.jsx
- Wedit-Client/src/components/editpage/ImgContainer.jsx
- Wedit-Client/src/components/editpage/InfoContainer.jsx
- Wedit-Client/src/components/editpage/Logo.jsx
- Wedit-Client/src/components/editpage/NameContainer.jsx
- Wedit-Client/src/components/editpage/NavButton.jsx
- Wedit-Client/src/components/editpage/OptSelection.jsx
- Wedit-Client/src/pages/AccountInfoPage.jsx
- Wedit-Client/src/pages/EditPage.jsx
- Wedit-Client/src/pages/GalleryPhotoSelectionPage.jsx
- Wedit-Client/src/pages/LoadingPage.jsx
- Wedit-Client/src/pages/MainPhotoSelectionPage.jsx
- Wedit-Client/src/pages/OptionSelectionPage.jsx
Closes #32
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
제작페이지 기능 추가
필수정보 페이지 컴포넌트, 기존 제작페이지 컴포넌트 별도 파일로 위치 이동
제작페이지와 사진선택페이지 theme사용 color변경
1. 필수정보 페이지 이름입력, 장소/시간, 사진첨부 컴포넌트로 별도 분리
2. 사진선택페이지에서 선택된 사진 필수정보 페이지로 전달 후 프리뷰 구현
3. 이전/다음 버튼 페이지 연결 (축의금 선택 시에만 축의금 계좌 정보 페이지로 이동)
4. 유효성 검사 구현
5. 다음 버튼 활성화
> [Feat/#32] "제작페이지 기능 추가"

- Wedit-Client/src/assets/icons/DropdownIcon.svg
- Wedit-Client/src/components/WeddingInvitationPage/congratulatory-money.jsx
- Wedit-Client/src/components/WeddingInvitationPage/gallery.jsx
- Wedit-Client/src/components/WeddingInvitationPage/guest-book-modal.jsx
- Wedit-Client/src/components/WeddingInvitationPage/guest-book.jsx
- Wedit-Client/src/components/WeddingInvitationPage/location.jsx
- Wedit-Client/src/components/WeddingInvitationPage/required-information.jsx
- Wedit-Client/src/components/WeddingInvitationPage/rsvp-modal.jsx
- Wedit-Client/src/components/WeddingInvitationPage/rsvp.jsx
- Wedit-Client/src/pages/WeddingInvitationPage.jsx
Closes #43
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
청첩장 페이지 반응형 및 Skeleton UI
참석의사 전달하기 Modal 드롭다운 추가 및 수정
1. 청첩장 페이지 세팅된 컬러 적용
2. 신랑 신부측 선택 드롭다운 추가
3. 추가 인원 선택 드롭다운 수정
4. 청첩장 페이지 이미지 반응형
5. 청첩장 페이지 이미지 Skeleton UI 추가
6. 방명록 컴포넌트 Skeleton UI 추가
> [Feat/#43] 청첩장 페이지 반응형 구현

- Wedit-Client/src/components/mainpage/MainBannerSlider.jsx
- Wedit-Client/src/components/mainpage/Skeleton.jsx
- Closes #47 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
배너 스켈레톤 UI 구현
1. 배너 스켈레톤 UI 생성
2. 애니메이션 적용
3. 모든 이미지 로딩 완료 시 스켈레톤 UI 꺼짐
https://github.com/user-attachments/assets/9460a1a7-8858-4254-8834-bb5e0a165bab
> [Feat/#47] 배너 스켈레톤 UI 구현

- Wedit-Client/src/App.jsx
- Wedit-Client/src/components/analysispage/Header.jsx
- Wedit-Client/src/components/analysispage/ParticipantsSummary.jsx
- Wedit-Client/src/components/analysispage/Section.jsx
- Wedit-Client/src/components/analysispage/VisitorsCount.jsx
- Wedit-Client/src/pages/AnalysisPage.jsx
- Closes #48 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
분석 페이지 UI 구현
1. 헤더, 푸터 구현 완료
2. 섹션(방문자 수/참석자 요약) 완료
3. 방문자 수 props로 받게 설정해뒀습니다
4. chart.js 컴포넌트 만드셔서 ParticipantsSummary.jsx에 참석자 요약 title 밑에 조건부로 렌더링 하시면 됩니다
(아님 편하신대로,,!👍🏻)
> [Feat/#48] 분석 페이지 UI 구현

- Wedit-Client/package.json
- Wedit-Client/src/apis/api/user.js
- Wedit-Client/src/apis/utils/apiIntance.js
- Wedit-Client/yarn.lock
- Closes #63 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
apiInstance 설정
1. apiInstance 설정 완료
2. env 파일 업데이트 완료(노션 확인 후 각자 업데이트)
3. api 연결 테스트 완료(테스트 완료 후 파일은 지움)
4. axios 모듈 설치 완료 (yarn install 하고 api 작업)
https://velog.io/@hsk10271/TIL-33
https://ghost4551.tistory.com/163
위 글 참고하여 services 폴더 등 자유롭게 추가하여 작업하세요 !
> [Feat/#63] apiInstance 설정

- netlify.toml
> netlify 파일 리디렉션 추가

- package.json
- src/components/mypage/Invitation.jsx
- src/pages/HomePage.jsx
- src/store/authState.js
- vite.config.js
- yarn.lock
- Closes #65 
어떤 변경 사항이 있나요?
-   [x] 버그 수정
-   [ ] 리팩토링
쿠키 설정, https 설정
1. recoil-persist 설치
2. vite-plugin-mkcert 설치(로컬 https 관련 모듈)
3. vite.config.js 수정(로컬 설정시 참고)
4. 기타 로그인 로직 수정(쿠키 관련 테스트)
> [Feat/#65] 쿠키 설정, https 설정

- src/apis/api/decisions.js
- src/apis/utils/apiIntance.js
- src/components/WeddingInvitationPage/RSVPModal.jsx
- src/components/WeddingInvitationPage/rsvp-modal.jsx
- src/components/WeddingInvitationPage/rsvp.jsx
Closes #66
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
참석의사 등록 API 연결
1. rsvp modal 참석의사 등록 API 연결
테스트 완료
> [Feat/#66] 참석의사 등록 API

- src/apis/api/my.js
- src/components/mypage/ActionButtons.jsx
- src/components/mypage/LinkModal.jsx
- src/components/mypage/MakingInvitation.jsx
- Closes #76 
- Closes #77 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
배포링크 생성 API, 청첩장 삭제 구현 API
1. 배포링크 생성 API 연결
2. 링크 복사 기능 동작 확인
3. 청첩장 삭제 API 연결
4. 11개 이상일 때 초기 청첩장 delete 확인
5. 마이페이지에 11번째에 추가된 청첩장 반영 확인
> [Feat/#76] 배포링크 생성 API, 청첩장 삭제 구현 API

- src/apis/api/comments.js
- src/components/WeddingInvitationPage/GuestBook.jsx
Closes #78
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
방명록 등록 API 연결
1. 특정 청첩장의 방명록 조회 API 연결 
2. 무한 스크롤 구현 
3. 중복 요청 방지 구현 
테스트 완료
> [Feat/#78] 방명록 조회 API

- src/App.jsx
- src/apis/api/patchInvitation.js
- src/components/editpage/ImgContainer.jsx
- src/components/editpage/ThemeSelectModal.jsx
- src/components/mypage/ActionButtons.jsx
- src/pages/AccountInfoPage.jsx
- src/pages/EditPage.jsx
- src/pages/GalleryPhotoSelectionPage.jsx
- src/pages/MainPhotoSelectionPage.jsx
- src/pages/OptionSelectionPage.jsx
Closes #81 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
특정 청첩장 정보를 불러와서 세팅, 청첩장 수정 API 연결
1. 청첩장 수정 API 연결 구현
2. 서버에서 받아온 이미지를 base64형태로 변환
3. 각 id에 맞는 청첩장 수정페이지 경로 설정
4. 새 청첩장 만들 시 초기화 설정 추가
사진 수정 포함
사진 수정 미포함
> [Feat/#81] "청첩장 수정 API 연결"

- src/App.jsx
- src/apis/api/patchInvitation.js
- src/components/WeddingInvitationPage/GuestBook.jsx
- src/components/WeddingInvitationPage/rsvp.jsx
- src/components/editpage/ImgContainer.jsx
- src/components/editpage/ThemeSelectModal.jsx
- src/components/mypage/ActionButtons.jsx
- src/pages/AccountInfoPage.jsx
- src/pages/EditPage.jsx
- src/pages/GalleryPhotoSelectionPage.jsx
- src/pages/MainPhotoSelectionPage.jsx
- src/pages/OptionSelectionPage.jsx
- src/pages/WeddingInvitationPage.jsx
Closes #89
어떤 변경 사항이 있나요?
-   [x] 버그 수정
-   [ ] 리팩토링
방명록 조회 오류 수정
방명록, 참석의사 등록 오류 수정 
1. 방명록 옵션 선택에 따른 렌더링 조건 추가 -> 선택 안 하면 렌더링 안됨 
2. 방명록 데이터 없을 시 '작성된 방명록이 없습니다.' 안내 -> 방명록 작성 후 새로고침하면 반영됨 
3. 방명록 등록 invitationId 전달 오류 수정
4. 참석의사 옵션 선택에 따른 렌더링 수정 (guestBookOption -> decisionOption)
5. 참석의사 등록 invitationId 전달 오류 수정
> [Fix/#89] 방명록 조회 오류 

- src/components/analysispage/ParticipantsSummary.jsx
- src/components/analysispage/Section.jsx
- src/pages/AnalysisPage.jsx
Closes #97
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
AnalysisPage 반응형 수정
1. 전체 화면 꽉 차도록
2. 화면 작아질 시 차트 안 넘치게 margin, height 수정
> [Refactor/#97] 분석보기 페이지 반응형 수정 

- src/components/mypage/Content.jsx
- src/components/mypage/LinkModal.jsx
- src/components/mypage/MakingInvitation.jsx
- src/components/mypage/MyPageSection.jsx
- src/pages/MyPage.jsx
Closes #100
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
MyPage, LinkModal 반응형 수정
1. 전체 화면 꽉 차도록
2. 화면 작아질 시 margin, height 수정
3. 배포 링크 모달 font size 수정
> [Refactor/#100] 마이페이지 반응형 수정 

- src/components/loginpage/Background.jsx
- src/pages/LoginPage.jsx
- src/styles/globalStyle.js
Closes #103
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
LoginPage 반응형 수정
1. 태블릿, 모바일 사이즈 전체 화면 꽉 차도록
2. 글로벌스타일에 -webkit-appearance: none; 추가
> [Refactor/#103] 로그인 페이지 반응형 수정

- src/components/loginpage/LoginButton.jsx
- src/styles/globalStyle.js
Webkit 이슈 수정
1. -moz-appearance: none; 추가
2. appearance: none; 추가
> [Refactor/#103] Webkit 이슈 수정

- src/components/mainpage/LoginButton.jsx
- src/components/mainpage/MainBannerSidebar.jsx
- src/components/mainpage/MainPageFooter.jsx
- src/components/mainpage/MainPageHeader.jsx
- src/components/mainpage/MainPageSection.jsx
- src/components/mainpage/PreviewBox.jsx
- src/pages/HomePage.jsx
- yarn.lock
- #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
메인페이지 반응형 1차
> [Style/#104] 메인페이지 반응형 1차

- src/components/mainpage/MainBannerSidebar.jsx
- src/components/mainpage/MainPageFooter.jsx
- src/components/mainpage/MainPageHeader.jsx
- src/components/mainpage/MainPageSection.jsx
- src/components/mainpage/PreviewBox.jsx
- src/components/mainpage/Skeleton.jsx
- #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
메인페이지 반응형 2차 수정
> [Style/#104] 메인페이지 반응형 2차 수정

- src/components/editpage/ImgContainer.jsx
- src/components/editpage/InfoContainer.jsx
- src/components/editpage/Logo.jsx
- src/components/editpage/NameContainer.jsx
- src/components/editpage/NavButton.jsx
- src/components/editpage/OptSelection.jsx
- src/pages/AccountInfoPage.jsx
- src/pages/EditPage.jsx
- src/pages/OptionSelectionPage.jsx
Closes #92
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
제작 페이지 반응형 수정 
1. 필수 정보 입력 페이지 반응형 수정
2. 옵션 선택 페이지 반응형 수정
3. 계좌 정보 입력 페이지 반응형 수정
> [Refactor/#92] 제작 페이지 반응형 수정 

- src/components/analysispage/Header.jsx
- src/components/analysispage/ParticipantsSummary.jsx
- src/components/analysispage/Section.jsx
- src/components/analysispage/VisitorsCount.jsx
- src/components/editpage/ImgContainer.jsx
- src/components/editpage/InfoContainer.jsx
- src/components/editpage/Logo.jsx
- src/components/editpage/NameContainer.jsx
- src/components/editpage/NavButton.jsx
- src/components/editpage/OptSelection.jsx
- src/components/loginpage/LoginButton.jsx
- src/components/mainpage/MainPageFooter.jsx
- src/components/mypage/ActionButtons.jsx
- src/components/mypage/Content.jsx
- src/components/mypage/HomeButton.jsx
- src/components/mypage/Invitation.jsx
- src/components/mypage/InvitationButton.jsx
- src/components/mypage/LogoutButton.jsx
- src/components/mypage/MakingInvitation.jsx
- src/components/mypage/MyPageHeader.jsx
- src/pages/AccountInfoPage.jsx
- src/pages/EditPage.jsx
- src/pages/LoginPage.jsx
- src/pages/OptionSelectionPage.jsx
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
모바일 사이즈 반응형 수정
> [Refactor/#92] 반응형 수정

- src/components/mainpage/MainBannerSidebar.jsx
- src/components/mainpage/MainPageFooter.jsx
- src/components/mainpage/MainPageHeader.jsx
- src/components/mainpage/MainPageSection.jsx
- src/components/mainpage/PreviewBox.jsx
- src/components/mainpage/Skeleton.jsx
- src/pages/HomePage.jsx
- #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
메인페이지 반응형 3차 수정
> [style/#104] 메인페이지 반응형 3차 수정

- index.html
- #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
메인페이지 반응형 4차 수정
> [Style/#104] 메인페이지 반응형 4차 수정

- src/apis/api/user.js
- src/components/mainpage/LoginButton.jsx
- src/components/mainpage/MainPageHeader.jsx
- src/components/mainpage/MainPageSection.jsx
- src/components/mainpage/PreviewBox.jsx
- src/components/mainpage/PreviewInvitationButton.jsx
- src/styles/globalStyle.js
- #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
메인페이지 반응형 5차 수정
> [Style/#104] 메인페이지 반응형 5차 수정

- src/components/mainpage/MainBannerSidebar.jsx
- src/components/mainpage/MainPageFooter.jsx
- Closes #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
메인페이지 반응형 6차 수정
> [Style/#104] 메인페이지 반응형 6차 수정

- src/components/mainpage/CreateInvitationButton.jsx
- #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
메인페이지 반응형 7차 수정
> [Style/#104] 메인페이지 반응형 7차 수정

- src/pages/LoadingPage.jsx
Closes #102 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
로딩페이지 반응형 수정
> [Feat/#102] "로딩페이지 반응형 수정"

- src/styles/globalStyle.js
- #104 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
메인페이지 반응형 8차 수정
> [Style/#104] 메인페이지 반응형 8차 수정

- src/components/mainpage/PreviewInvitationButton.jsx
- src/pages/PreviewInvitationPage.jsx
- Closes #122 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
미리보기페이지 반응형 1차 수정
> [Style/#122] 미리보기페이지 반응형 1차 수정

- src/pages/LoadingPage.jsx
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
로딩페이지 반응형 3차 수정
>  [style]/#102] "로딩페이지 반응형 3차 수정"

- src/components/PhotoSelectionPage/PageIndicator.jsx
- src/components/PhotoSelectionPage/PhotoSelectionButton.jsx
- src/pages/GalleryPhotoSelectionPage.jsx
- src/pages/MainPhotoSelectionPage.jsx
Closes #93 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
사진선택 페이지 반응형 1차 수정
> [Feat/#93] "사진선택페이지 반응형 수정"

- src/components/mypage/ActionButtons.jsx
- src/components/mypage/Content.jsx
- src/components/mypage/HomeButton.jsx
- src/components/mypage/Invitation.jsx
- src/components/mypage/InvitationButton.jsx
- src/components/mypage/LinkModal.jsx
- src/components/mypage/LogoutButton.jsx
- src/components/mypage/MakingInvitation.jsx
- src/components/mypage/MyPageHeader.jsx
- Closes #125 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
마이페이지 반응형 1차 수정
> [Style/#125] 마이페이지 반응형 1차 수정

- src/components/editpage/ImgContainer.jsx
- src/styles/globalStyle.js
Closes #127 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 리팩토링
달력, 시간 팝업 사이즈 조정과 이미지 프리뷰 수정
>  [Refactor #127] "datepicker 수정" 

- src/components/mypage/LinkModal.jsx
- #125 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
마이페이지 반응형 2차 수정
> [Style/#125] 마이페이지 반응형 2차 수정

- src/components/mypage/LinkModal.jsx
- #125 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
마이페이지 반응형 3차 수정
> [Style/#125] 마이페이지 반응형 3차 수정

- src/components/mypage/LinkModal.jsx
- #125 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
마이페이지 반응형 4차 수정
> [Style/#125] 마이페이지 반응형 4차 수정

- src/components/loginpage/Background.jsx
- src/components/loginpage/LoginButton.jsx
- src/pages/LoginPage.jsx
- #133 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
로그인페이지 반응형 1차 수정
> [Style/#133] 로그인페이지 반응형 1차 수정

- src/components/loginpage/Background.jsx
- #133 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
로그인 페이지 반응형 3차 수정
> [Style/#133] 로그인 페이지 반응형 3차 수정

- src/components/loginpage/Background.jsx
- #133 
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
로그인페이지 반응형 4차 수정
> [Style/#133] 로그인페이지 반응형 4차 수정

- src/components/WeddingInvitationPage/CongratulatoryMoney.jsx
- src/components/WeddingInvitationPage/GuestBookModal.jsx
- src/components/WeddingInvitationPage/RSVPModal.jsx
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
변동된 크기 재수정
> [Refactor/#94]

- src/pages/MainPhotoSelectionPage.jsx
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
1.
2.
3.
> 사진선택페이지 반응형 3차 수정

- src/pages/LoadingPage.jsx
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
1.
2.
3.
> style: 로딩페이지 반응형 4차 수정

- src/pages/OptionSelectionPage.jsx
어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 리팩토링
1.
2.
3.
> style: 설명문구 수정
